### PR TITLE
Update to python3/2

### PR DESCRIPTION
**Pull request by melund**
Hi Todd

I also update the spm1d library. As with the rft1d, all future code can be written in python3, and it will remain compatible with legacy python (2.7) using the python-future package. 

As with rft1d the PR includes a test script that runs all your examples saving all figures to a pdf file. 

```
[py3] C:\Users\mel\Documents\GitHub\spm1d\tests>py.test
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: C:\Users\mel\Documents\GitHub\spm1d, inifile: pytest.ini
collected 55 items

test_examples.py .......................................................

========================= 55 passed in 21.60 seconds ==========================

[py3] C:\Users\mel\Documents\GitHub\spm1d\tests>activate py2
Deactivating environment "C:\Users\mel\Anaconda3\envs\py3"...
Activating environment "C:\Users\mel\Anaconda3\envs\py2"...

[py2] C:\Users\mel\Documents\GitHub\spm1d\tests>py.test
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: C:\Users\mel\Documents\GitHub\spm1d, inifile: pytest.ini
collected 55 items

test_examples.py .......................................................

========================= 55 passed in 28.59 seconds ==========================
```

Here are the two PDF files so you can compare output. 

[spm1d_examples_py2.7.pdf](https://github.com/0todd0000/spm1d/files/49191/spm1d_examples_py2.7.pdf)
[spm1d_examples_py3.5.pdf](https://github.com/0todd0000/spm1d/files/49192/spm1d_examples_py3.5.pdf)

### CODE REVIEW

**Comment by melund** [comment]
Many of the changed were done automatically. So there are many places where the code could be simplified. Especially the heavy use of 'list()' could be removed in many cases. I often legal to use the use the python3 generator objects.

**Comment by 0todd0000** [comment]
HI Morten, thank you for all of the changes.  I had a quick look at the edits and everything looks fine, but I have two questions:

1)  By when would you like me to approve the pull request?   I'm out of town on business and will be busy after that until the holiday break, so won't be able to test things properly until at least January.   

2)  Could you explain why you have added conda support?  I am somewhat reluctant to add support for yet another package management tool.

Todd

**Comment by melund** [comment]
Hi Todd. 

There is no hurry. I can use the python 3 version already, and so can anyone else if they are willing to install it with conda from here https://anaconda.org/melund/spm1d

Regarding conda, then I don't think it is just another package management tool. It is the [official recommended tool](https://python-packaging-user-guide.readthedocs.org/en/latest/current/) for stuff that is not just pure python. Conda was started by the guys behind Numpy (http://technicaldiscovery.blogspot.dk/2013/12/why-i-promote-conda.html) . The primary motivation was to create a python packaging tool that can also install non-pyton stuff. This is very import for the scientific Python community where we rely on many tools that are not pure python. You use hdf5 for example. 

Essentially, Conda is the best thing that ever happened to someone like me who is forced to used Windows. 

Of course, the files don't have to be part of your repository. But that is what many other libraries do. If you don't want it in, then I will rebase and remove the commits from the PR.

**Comment by 0todd0000** [comment]
Hi Morten, Conda looks good.  Have you tried Canopy?  From what I've seen Canopy might be even more convenient for Windows users, with one-click GUI-based package installing including non-Python packages like OpenCV.

If we were to add Conda support, would you be willing to debug problems that might arise?

Last, regarding your license change request:  what applications do you have in mind for spm1d / rft1d?   If you have purely academic applications in mind then we'd certainly consider giving you a LGPL license.  But if you want to create a commercial application we may prefer to partner.

Cheers,
Todd

**Comment by 0todd0000** [comment]
Hi Morten, I'm writing to follow-up on three issues related to your pull request.

1.  Conda:  are you willing to be involved in Conda support?  If not we are somewhat reluctant to offer support for Conda and not for alternative distributions. 

2.  Python 3:  are you willing to be involved in Python 3 support?  We will eventually make the transition to Python 3 in a future major release, likely in 2016 or 2017, but since many distributions and scientists still use Python 2.7 (and indeed since Anaconda still offers a 2.7 version) we do not feel an urgent need to support Python 3 unless we can have a partner who will help us support it.

3.  License:  we will keep the license as is for now, but please feel free to contact us privately any time if you prefer an alternative license for your applications.

Thank you very much for the PDF-generating script.  This appears to be very useful and we do hope to incorporate it soon.  We have unittest functions which perform a similar iterative test run over all scripts, but these do not generate PDFs.  We'll certainly look into improving this automated PDF functionality.


Regards,

Todd

**Comment by melund** [comment]
Hi Todd. Sorry for late reply. I thought I sent you an answer to your post in December but I may have forgotten to press submit. 

I have no special applications in mind, but I did plan to use it in the data analysis for my next publication. The GPL licence is a deal breaker in the long run, so I am sorry you have no plans of changing. Just giving me a special licence wouldn't help, as I wouldn't be able to share my scripts with anyone. Having to change the licence of all my code just because I do `import smp1d` is crazy. 

How many of your users actually comply with your licence? LGPL would solve that.

I would love to help out with the Python3 move if I can. I think a python2/3 compliant code base is the way forward. 

Regarding Conda support, I don't mind if it was removed it from the repo. It is not hugely important, and recipe files could be hosted elsewhere. There is also a new project I just heard about ( https://conda-forge.github.io/ ) which tries to host recipes to build conda packages on free CI services.  That may be a better option. 

/Morten

**Comment by 0todd0000** [comment]
Hi Morten, 

Thanks again for your suggestions and pull request.  Please note that today I released the next major version of **spm1d** (version 0.4), and this new version finally supports Python 3.5.  I used many of your edits, but since there were a variety of other core edits it's not easy to process the changes through this pull request. 

I've started to use Anaconda more recently, and I quite like it.  I'm tempted to offer Anaconda support for **spm1d**, but Anaconda seems quite a bit buggier than Enthought Canopy.  Spyder in particular causes repeated and unpredictable kernel crashes (Windows 32 bit), so I'm a bit reluctant to devote too much time to it.  Have you had better experiences with Anaconda for Linux or Mac?

Todd

**Comment by melund** [comment]
Hi Todd

I am glad I could help in some little way, even though PR wasn't used. And great that Python 3 is covered now. You should consider adding the project to the Python 3 statement: https://python3statement.github.io .If anything it is good exposure for the project.

Anacoda support would be a great thing. I don't think Anaconda is more buggy than Enthought Python Distribution. Spyder may be buggier (I also only have experience with Windows), but Spyder is not associated with Anaconda (even though one of the core developers currently work for Contiuum Inc).  Spyder is an open source project which existed long before Anaconda.  Spyder just released version 3 this week, but if you still have problems, you really should post an issue here: https://github.com/spyder-ide/spyder

[Conda-forge](https://conda-forge.github.io/) is a new development, which didn't exist when I created the conda packages for SPM1D last year. It can best be described a framework to create a community repository of conda-packages. Every conda-recipe is a git repository ([example](https://github.com/conda-forge/xonsh-feedstock)), which will automatically build the package for all platform.  It also has the benefit that the recipe is separate from the project. Something which I recall was important to you.

If you like, I could help create the recipes to add spm1d to conda-forge. I have done something similar for few other projects, so it shouldn't be much trouble. 

/Morten

**Comment by ivoflipse** [comment]
Hi Todd, 

I don't use Spyder (anymore), but conda made it a lot easier to develop, test and deploy our software. 

@melund made a recipe for you on conda-forge, which doesn't require any additional work from your part
https://github.com/conda-forge/staged-recipes/pull/1702

You could be listed as a maintainer, but that's optional. This should help expose your package to Anaconda users, though for the time being they'd have to explicitly point to the conda-forge channel in order to get it. Like `conda install -c conda-forge  spm1d`

**Comment by melund** [comment]
@ivoflipse Well spotted. It is ready, just waiting for the conda-forge core-dev to convert it to a feedstock recipe. I will add @0todd0000 if wants to.

**Comment by melund** [comment]
@ivoflipse @0todd0000 .. So the feedstock for spm1d just went live https://github.com/conda-forge/spm1d-feedstock

**Comment by adam2392** [comment]
Was this ever merged into the repo for Python3 support? If not, is there a date in mind for it?

**Comment by 0todd0000** [comment]
This branch was not merged, but the current master branch does indeed support Python 3.  I didn't merge this branch with the master because the 2/3 conversions were automated in this branch. I wanted to check all changes in detail to make sure they were (a) necessary and also (b) compatible with both 2/3.

**Pull request closed without merging**
